-- A. Customer Journey
-- 1. Based off the 8 sample customers provided in the sample subscriptions table below, 
-- write a brief description about each customer’s onboarding journey.
-- Answer:
-- B. Data Analysis Questions
-- 1. How many customers has Foodie-Fi ever had?
-- Answer:
-- 2. What is the monthly distribution of trial plan start_date values for our dataset - 
-- use the start of the month as the group by value
-- Answer:
-- 3. What plan start_date values occur after the year 2020 for our dataset? 
-- Show the breakdown by count of events for each plan_name.
-- Answer:
-- 4. What is the customer count and percentage of customers who have churned rounded to 1 decimal place?
-- Answer:
-- 5. How many customers have churned straight after their initial free trial - 
-- what percentage is this rounded to the nearest whole number?
-- Answer:
-- 6. What is the number and percentage of customer plans after their initial free trial?
-- Answer:
-- 7. What is the customer count and percentage breakdown of all 5 plan_name values at 2020-12-31?
-- Answer:
-- 8. How many customers have upgraded to an annual plan in 2020?
-- Answer:
-- 9. How many days on average does it take for a customer to upgrade to an annual plan from the day they join Foodie-Fi?
-- Answer:
-- 10. Can you further breakdown this average value into 30 day periods (i.e. 0-30 days, 31-60 days etc)
-- Answer:
-- 11. How many customers downgraded from a pro monthly to a basic monthly plan in 2020?
